[package]
name = "ic-crypto-internal-seed"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-crypto-sha = { path = "../../../sha" }
ic-types = { path = "../../../../types/types" }
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3"
serde = "1.0.130"
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }
