[package]
name = "ic-icrc1-client"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "ICRC-1 compliant client library."
edition = "2018"

[dependencies]
async-trait = "0.1.53"
candid = "0.7.10"
ic-base-types = { path = "../../../types/base_types" }
ic-icrc1 = { path = "../" }
ic-ledger-core = { path = "../../ledger_core" }
serde = "1.0"