include:
- local: /gitlab-ci/config/00--child-pipeline-root.yml

.ubuntu-nix-docker-protected:
  image:
    # Use the docker image without nix-shell
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:939cda350b1e59089777b0294132040cd8311e25c792b18c147a69203419871a"
  extends:
    - .ubuntu-nix-docker
  tags:
    - dfinity-launch
