bazel-test-all:
  extends:
    - .ubuntu-nix-docker
    - .bazel-rules-pipeline
  tags:
    - dfinity
    - docker
    - ubuntu
    # Run in ZH since BuildFarm is in ZH
    - zh
  image:
    # use the docker image without nix-shell as docker-run uses it too.
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:3378fa5822b966997329e5d59dc2b9da053a4977741b7f701295a9152af8fc83"
  stage: test
  needs: []
  artifacts:
    when: always
    paths:
      - bazel-build-log*.json
    reports:
      junit: bazel-testlogs-gitlab/**/test.xml
  script:
    - set -euo pipefail
    - |
      bazel version
      bazel --output_base "/cache/bazel-output/${CI_CONCURRENT_ID}" test --config ci "${BAZEL_TARGET:-...}" 2>&1 | sed --unbuffered 's/\(.*Streaming build results to:.*\)/\o33[92m\1\o33[0m/'
  after_script:
    - cp -R "$(readlink -f bazel-testlogs)" bazel-testlogs-gitlab
    - !reference [after_script]
