bazel-test-all:
  extends:
    - .ubuntu-nix-docker
    - .bazel-rules-pipeline
  tags:
    - dfinity
    - docker
    - ubuntu
    # Run in ZH since BuildFarm is in ZH
    - zh
  image:
    # use the docker image without nix-shell as docker-run uses it too.
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:97c45456ea9c071ee12d8ff02ea360c4c0df66519a48c3885103c4645f84eb53"
  stage: test
  needs: []
  artifacts:
    when: always
    paths:
      - bazel-build-log*.json
    reports:
      junit: bazel-testlogs-gitlab/**/test.xml
  script:
    - set -euo pipefail
    - bazel version
    - mkdir -p "${HOME}/.aws"
    - ln -s "${AWS_SHARED_CREDENTIALS_FILE}" "${HOME}/.aws/credentials"
    - >
      bazel
      --output_base "/cache/bazel-output/${CI_CONCURRENT_ID}"
      test
      --config ci
      --build_metadata=BUILDBUDDY_LINKS="[GitLab CI Job](${CI_JOB_URL})"
      "${BAZEL_TARGET:-...}"
      2>&1 |
      sed --unbuffered 's/\(.*Streaming build results to:.*\)/\o33[92m\1\o33[0m/'
  after_script:
    - | 
      echo -e "\033[0;31m"
      echo -e "*************************************************************"
      echo -e "*** NEED BAZEL HELP? See go/bazel-guide and #project-bazel **"
      echo -e "*************************************************************"
      echo -e "\033[0m"
    -  cp -R "$(readlink -f bazel-testlogs)" bazel-testlogs-gitlab
    - !reference [after_script]
