.after-script-test:
  extends:
    - .ubuntu-nix-docker-k8s
    - .rules-after-script-test
  needs: []  # don't wait on other jobs
  stage: test
  script:
    - |
      set -eExuo pipefail
      export ROOT_PIPELINE_ID=${PARENT_PIPELINE_ID:-$CI_PIPELINE_ID}

      if [[ $DO_SHELLCHECK == "true" ]]; then
        # Shell check should run in the repo root otherwise it cannot follow shellcheck
        # source directives
        cd "${CI_PROJECT_DIR}"
        shellcheck -x gitlab-ci/src/after_script/*.sh
      fi

      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" "$CI_JOB_NAME" -- "${CI_PROJECT_DIR}"/gitlab-ci/src/after_script/after_script.sh

after-script-test-monolithic-image:
  variables:
    DO_SHELLCHECK: "true"
  extends:
    - .after-script-test

after-script-test-bazel-image:
  image:
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build-bazel:7b3c7a5549ae2d13b4f5cadfb5245a4884236debd4078198e540aa05d871ae27"
  variables:
    DO_SHELLCHECK: "false"
  extends:
    - .after-script-test
