[package]
name = "ic-crypto-internal-bls12381-serde-miracl"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2018"

[dependencies]
miracl_core_bls12381 = { version = "4.1.2", package = "miracl_core_bls12381" }
ic-crypto-internal-bls12-381-type = { path = "../../type" }
ic-crypto-internal-types = { path = "../../../types" }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
hex = "0.4.2"
rand = "0.8"

[[bench]]
name = "serde"
harness = false
