[package]
name = "ic-ledger-client-core"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
edition = "2018"

[dependencies]
candid = "0.7.4"
ic-certified-vars = { path = "../../certified_vars" }
dfn_protobuf = {path = "../../rust_canisters/dfn_protobuf"}
ic-canister-client = { path = "../../canister_client" }
ic-ledger-core = { path = "../ledger_core" }
ic-types = { path = "../../types/types" }
ledger-canister = { path = "../ledger_canister" }
log = "0.4.14"
on_wire = {path = "../../rust_canisters/on_wire"}
rusqlite = "~0.25.4"
serde = "1.0"
tokio = { version = "1.15.0", features = ["full"] }
url = "2.2.1"

[dev-dependencies]
actix-rt = "2.2.0"
actix-web = { version = "4.0.1", default_features = false, features = ["macros", "compress-brotli", "compress-gzip", "cookies"] }
ic-ledger-client-core-test-utils = { path = "test_utils" }