[package]
name = "ic-sns-init"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.57"
candid = "0.7.4"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-nns-constants = { path = "../../nns/constants" }
ic-sns-governance = { path = "../governance" }
ic-sns-root = { path = "../root" }
ic-sns-swap = { path = "../swap" }
ledger-canister = { path = "../../rosetta-api/ledger_canister" }
maplit = "1.0.2"
num = "0.4.0"
prost = "0.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
serde_yaml = "0.8.24"

[dev-dependencies]
assert_approx_eq = "1.1.0"
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-sns-init-proto-generator = { path = "./proto_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
tempfile = "3.1.0"
