[package]
name = "ic-canister-client-sender"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-crypto-sha = { path = "../../crypto/sha" }
# TODO(CRP-909): use public crate (not the internal one) for ecdsa-secp256k1 when available.
ecdsa-secp256k1 = { path = "../../crypto/internal/crypto_lib/basic_sig/ecdsa_secp256k1", package = "ic-crypto-internal-basic-sig-ecdsa-secp256k1"}
ic-interfaces = { path = "../../interfaces" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-types = { path = "../../types/types" }
ed25519-dalek = "1.0.1"

