[package]
name = "ic-crypto-internal-bls12-381-type"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miracl_core_bls12381 = { version = "4.1.2", package = "miracl_core_bls12381" }
bls12_381 = { version = "0.7.0", default-features = false, features = ["groups", "pairings", "alloc", "experimental", "zeroize"] }
pairing = "0.22"
subtle = "2.4"
sha2 = "0.9"
rand = "0.8"
rand_chacha = "0.3"
lazy_static = "1.4"
zeroize = { version = "1", features = ["zeroize_derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = { version = "0.2" }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
ic-crypto-internal-types = { path = "../../types" }
hex = "0.4"

[[bench]]
name = "ops"
harness = false
